/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Tools.FonctionsMetier;
import Entity.Labo;
import Entity.Secteur;
import Entity.Visiteurs;
import Model.ModelVisiteur;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kayum
 */
public class frmListerVisiteurs extends javax.swing.JFrame {

    
    FonctionsMetier fm;
    ModelVisiteur mdlVisiteur;
    /**
     * Creates new form frmListerVisiteurs
     */
    public frmListerVisiteurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisiteurs = new javax.swing.JTable();
        txtNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        txtCp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVille = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboLabo = new javax.swing.JComboBox<>();
        cboSecteur = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnInserer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnRaz = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblGsb = new javax.swing.JLabel();
        lblFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVisiteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVisiteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisiteursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVisiteurs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 780, 160));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 315, 134, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prénom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 357, -1, 10));
        getContentPane().add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 353, 134, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adresse ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 388, -1, -1));
        getContentPane().add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 384, 134, -1));

        txtCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpActionPerformed(evt);
            }
        });
        getContentPane().add(txtCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 419, 134, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Code postal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 423, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ville");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 314, -1, -1));
        getContentPane().add(txtVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 310, 200, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date d'embauche");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 352, -1, -1));
        getContentPane().add(cboLabo, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 383, 200, -1));
        getContentPane().add(cboSecteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 416, 200, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Laboratoire");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 388, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Secteur");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 419, -1, -1));

        btnInserer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn Insérer 2.png"))); // NOI18N
        btnInserer.setText("INSÉRER");
        btnInserer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsererMouseClicked(evt);
            }
        });
        getContentPane().add(btnInserer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 110, -1));

        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modifier2.png"))); // NOI18N
        btnModifier.setText("MODIFIER");
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 110, -1));

        btnRaz.setText("RAZ");
        btnRaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRazMouseClicked(evt);
            }
        });
        getContentPane().add(btnRaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 100, -1));

        txtDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 348, 200, 24));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Liste des visiteurs");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 34));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        lblGsb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gsb.png"))); // NOI18N
        getContentPane().add(lblGsb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pour visiteur.jpg"))); // NOI18N
        getContentPane().add(lblFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsererMouseClicked
        // TODO add your handling code here:
        
        if(txtNom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un nom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtAdresse.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une adresse", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtPrenom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un prenom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtVille.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une ville", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtCp.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un code postal", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDate.getDate().toString().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une date", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String ville = txtVille.getText();
            int cp = Integer.parseInt(txtCp.getText());
            String adresse = txtAdresse.getText();
            int labo = fm.getIdLaboByName(cboLabo.getSelectedItem().toString());
            int secteur = fm.getIdSecteurByName(cboSecteur.getSelectedItem().toString());
                    
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); 
            String dateEmb = format.format( txtDate.getDate() );
         
            Visiteurs unVisiteur = new Visiteurs(nom,
            prenom, adresse, cp, ville, dateEmb);
            // Insertion en BB du nouveau jeu
            fm.insertVisiteur(unVisiteur, labo, secteur);
            // On recharge le modèle car il y a un nouveau jeu
            mdlVisiteur.loadDatasVisiteur(fm.getAllVisiteurs());
            // On met à jour le modèle du JTable
            tblVisiteurs.setModel(mdlVisiteur);
        }
        
    }//GEN-LAST:event_btnInsererMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fm = new FonctionsMetier();
        // On crée notre modelJeux
        mdlVisiteur = new ModelVisiteur();
        // On charge les données dans le modèle
        mdlVisiteur.loadDatasVisiteur(fm.getAllVisiteurs());
        // On met à jour le modèle du JTable
        tblVisiteurs.setModel(mdlVisiteur);
        
        for (Labo labo : fm.getAllLabos())
        {
            cboLabo.addItem(labo.getNomLabo());
        }
        
        for (Secteur secteur : fm.getAllSecteurs())
        {
            cboSecteur.addItem(secteur.getNomSecteur());
        }
    }//GEN-LAST:event_formWindowOpened

    private void tblVisiteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisiteursMouseClicked
        try {
            // TODO add your handling code here:
            String nom = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 1).toString();
            String prenom = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 2).toString();
            String adresse = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 3).toString();
            String cp = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 4).toString();
            String ville = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 5).toString();
            String dateEmb = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 6).toString();
            String labo = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 7).toString();
            String secteur = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 8).toString();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(dateEmb);
            
            txtNom.setText(nom);
            txtPrenom.setText(prenom);
            txtAdresse.setText(adresse);
            txtCp.setText(cp);
            txtVille.setText(ville);
            cboLabo.setSelectedItem(labo);
            cboSecteur.setSelectedItem(secteur);
            txtDate.setDate(date);
            
        } catch (ParseException ex) {
            Logger.getLogger(frmListerVisiteurs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblVisiteursMouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
        // TODO add your handling code here:
        if(tblVisiteurs.getSelectedRowCount() == 0)
        {
         JOptionPane.showMessageDialog(null,
                    "Veuillez sélectionner un visiteur", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);   
        }
        else if(txtNom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un nom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtAdresse.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une adresse", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtPrenom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un prenom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtVille.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une ville", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtCp.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un code postal", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDate.getDate().toString().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une date", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String ville = txtVille.getText();
            int cp = Integer.parseInt(txtCp.getText());
            String adresse = txtAdresse.getText();
            int labo = fm.getIdLaboByName(cboLabo.getSelectedItem().toString());
            int secteur = fm.getIdSecteurByName(cboSecteur.getSelectedItem().toString());
            int id = Integer.parseInt(tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 0).toString());
                    
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); 
            String dateEmb = format.format( txtDate.getDate() );
         
            Visiteurs unVisiteur = new Visiteurs(nom,
            prenom, adresse, cp, ville, dateEmb);
            
            fm.modifierAction(unVisiteur, id, labo, secteur);
            
            mdlVisiteur.loadDatasVisiteur(fm.getAllVisiteurs());
            // On met à jour le modèle du JTable
            tblVisiteurs.setModel(mdlVisiteur);
        }
    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnRazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRazMouseClicked
        // TODO add your handling code here:
        
            txtNom.setText(null);
            txtPrenom.setText(null);
            txtAdresse.setText(null);
            txtCp.setText(null);
            txtVille.setText(null);
            cboLabo.setSelectedItem(null);
            cboSecteur.setSelectedItem(null);
            txtDate.setDate(null);
        
        
    }//GEN-LAST:event_btnRazMouseClicked

    private void txtCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListerVisiteurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRaz;
    private javax.swing.JComboBox<String> cboLabo;
    private javax.swing.JComboBox<String> cboSecteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFond;
    private javax.swing.JLabel lblGsb;
    private javax.swing.JTable tblVisiteurs;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCp;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
