/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.FonctionsMetier;
import Entity.Labo;
import Entity.Secteur;
import Entity.Visiteurs;
import Model.ModelVisiteur;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kayum
 */
public class frmListerVisiteurs extends javax.swing.JFrame {

    
    FonctionsMetier fm;
    ModelVisiteur mdlVisiteur;
    /**
     * Creates new form frmListerVisiteurs
     */
    public frmListerVisiteurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisiteurs = new javax.swing.JTable();
        txtNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        txtCp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVille = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboLabo = new javax.swing.JComboBox<>();
        cboSecteur = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnInserer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnRaz = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblGsb = new javax.swing.JLabel();
        lblFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblVisiteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVisiteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisiteursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVisiteurs);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adresse ");

        txtCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Code postal");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ville");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Embauche");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Labo");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Secteur");

        btnInserer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn Insérer 2.png"))); // NOI18N
        btnInserer.setText("INSERER");
        btnInserer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsererMouseClicked(evt);
            }
        });

        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modifier2.png"))); // NOI18N
        btnModifier.setText("MODIFIER");
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });

        btnRaz.setText("RAZ");
        btnRaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRazMouseClicked(evt);
            }
        });

        txtDate.setDateFormatString("yyyy-MM-dd");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Liste des visiteurs");

        lblGsb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gsb.png"))); // NOI18N

        lblFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pour visiteur.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(lblGsb)
                .addGap(125, 125, 125)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRaz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(317, 317, 317)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel7))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(txtCp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(cboSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(cboLabo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblFond, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10))
                    .addComponent(lblGsb)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnInserer)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifier)
                        .addGap(22, 22, 22)
                        .addComponent(btnRaz)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(cboLabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblFond, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsererMouseClicked
        // TODO add your handling code here:
        
        if(txtNom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un nom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtAdresse.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une adresse", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtPrenom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un prenom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtVille.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une ville", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtCp.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un code postal", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDate.getDate().toString().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une date", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String ville = txtVille.getText();
            int cp = Integer.parseInt(txtCp.getText());
            String adresse = txtAdresse.getText();
            int labo = fm.getIdLaboByName(cboLabo.getSelectedItem().toString());
            int secteur = fm.getIdSecteurByName(cboSecteur.getSelectedItem().toString());
                    
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); 
            String dateEmb = format.format( txtDate.getDate() );
         
            Visiteurs unVisiteur = new Visiteurs(nom,
            prenom, adresse, cp, ville, dateEmb);
            // Insertion en BB du nouveau jeu
            fm.insertVisiteur(unVisiteur, labo, secteur);
            // On recharge le modèle car il y a un nouveau jeu
            mdlVisiteur.loadDatasVisiteur(fm.getAllVisiteurs());
            // On met à jour le modèle du JTable
            tblVisiteurs.setModel(mdlVisiteur);
        }
        
    }//GEN-LAST:event_btnInsererMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fm = new FonctionsMetier();
        // On crée notre modelJeux
        mdlVisiteur = new ModelVisiteur();
        // On charge les données dans le modèle
        mdlVisiteur.loadDatasVisiteur(fm.getAllVisiteurs());
        // On met à jour le modèle du JTable
        tblVisiteurs.setModel(mdlVisiteur);
        
        for (Labo labo : fm.getAllLabos())
        {
            cboLabo.addItem(labo.getNomLabo());
        }
        
        for (Secteur secteur : fm.getAllSecteurs())
        {
            cboSecteur.addItem(secteur.getNomSecteur());
        }
    }//GEN-LAST:event_formWindowOpened

    private void tblVisiteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisiteursMouseClicked
        try {
            // TODO add your handling code here:
            String nom = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 1).toString();
            String prenom = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 2).toString();
            String adresse = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 3).toString();
            String cp = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 4).toString();
            String ville = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 5).toString();
            String dateEmb = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 6).toString();
            String labo = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 7).toString();
            String secteur = tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 8).toString();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(dateEmb);
            
            txtNom.setText(nom);
            txtPrenom.setText(prenom);
            txtAdresse.setText(adresse);
            txtCp.setText(cp);
            txtVille.setText(ville);
            cboLabo.setSelectedItem(labo);
            cboSecteur.setSelectedItem(secteur);
            txtDate.setDate(date);
            
        } catch (ParseException ex) {
            Logger.getLogger(frmListerVisiteurs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblVisiteursMouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
        // TODO add your handling code here:
        if(txtNom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un nom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtAdresse.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une adresse", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtPrenom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un prenom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtVille.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une ville", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtCp.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un code postal", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDate.getDate().toString().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir une date", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String ville = txtVille.getText();
            int cp = Integer.parseInt(txtCp.getText());
            String adresse = txtAdresse.getText();
            int labo = fm.getIdLaboByName(cboLabo.getSelectedItem().toString());
            int secteur = fm.getIdSecteurByName(cboSecteur.getSelectedItem().toString());
            int id = Integer.parseInt(tblVisiteurs.getValueAt(tblVisiteurs.getSelectedRow(), 0).toString());
                    
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); 
            String dateEmb = format.format( txtDate.getDate() );
         
            Visiteurs unVisiteur = new Visiteurs(nom,
            prenom, adresse, cp, ville, dateEmb);
            
            fm.modifierAction(unVisiteur, id, labo, secteur);
            
            mdlVisiteur.loadDatasVisiteur(fm.getAllVisiteurs());
            // On met à jour le modèle du JTable
            tblVisiteurs.setModel(mdlVisiteur);
        }
    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnRazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRazMouseClicked
        // TODO add your handling code here:
        
            txtNom.setText(null);
            txtPrenom.setText(null);
            txtAdresse.setText(null);
            txtCp.setText(null);
            txtVille.setText(null);
            cboLabo.setSelectedItem(null);
            cboSecteur.setSelectedItem(null);
            txtDate.setDate(null);
        
        
    }//GEN-LAST:event_btnRazMouseClicked

    private void txtCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListerVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListerVisiteurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRaz;
    private javax.swing.JComboBox<String> cboLabo;
    private javax.swing.JComboBox<String> cboSecteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFond;
    private javax.swing.JLabel lblGsb;
    private javax.swing.JTable tblVisiteurs;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCp;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
