/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.ConnexionBDD;

/**
 *
 * @author kayum
 */
public class frmMenu extends javax.swing.JFrame {

    ConnexionBDD cnxBdd;
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegion = new javax.swing.JButton();
        btnStatistiques = new javax.swing.JButton();
        btnListerVisiteurs = new javax.swing.JButton();
        btnVisiteursParRegion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegion.setText("Regions");
        btnRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegionMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 180, 53));

        btnStatistiques.setText("Statistiques");
        btnStatistiques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatistiquesMouseClicked(evt);
            }
        });
        btnStatistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistiquesActionPerformed(evt);
            }
        });
        getContentPane().add(btnStatistiques, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 180, 53));

        btnListerVisiteurs.setText("Visiteurs");
        btnListerVisiteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListerVisiteursMouseClicked(evt);
            }
        });
        getContentPane().add(btnListerVisiteurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 180, 53));

        btnVisiteursParRegion.setText("Visiteurs par regions");
        btnVisiteursParRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisiteursParRegionMouseClicked(evt);
            }
        });
        btnVisiteursParRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisiteursParRegionActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisiteursParRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 180, 53));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gsb.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 90));

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fond Accueil.jpg"))); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, 780, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cnxBdd = new ConnexionBDD();
    }//GEN-LAST:event_formWindowOpened

    private void btnStatistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistiquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatistiquesActionPerformed

    private void btnListerVisiteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListerVisiteursMouseClicked
        // TODO add your handling code here:
        frmListerVisiteurs frm = new frmListerVisiteurs();
        frm.setVisible(true);
    }//GEN-LAST:event_btnListerVisiteursMouseClicked

    private void btnStatistiquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistiquesMouseClicked
        // TODO add your handling code here:
        frmStatistiques frm = new frmStatistiques();
        frm.setVisible(true);
    }//GEN-LAST:event_btnStatistiquesMouseClicked

    private void btnRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegionMouseClicked
        // TODO add your handling code here:
        frmRegions frm = new frmRegions();
        frm.setVisible(true);
    }//GEN-LAST:event_btnRegionMouseClicked

    private void btnVisiteursParRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisiteursParRegionMouseClicked
        // TODO add your handling code here:
        frmInsererVisiteurRegion frm = new frmInsererVisiteurRegion();
        frm.setVisible(true);
    }//GEN-LAST:event_btnVisiteursParRegionMouseClicked

    private void btnVisiteursParRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisiteursParRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisiteursParRegionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListerVisiteurs;
    private javax.swing.JButton btnRegion;
    private javax.swing.JButton btnStatistiques;
    private javax.swing.JButton btnVisiteursParRegion;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
