/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.FonctionsMetier;
import Entity.Region;
import Entity.Secteur;
import Model.ModelRegion;
import javax.swing.JOptionPane;

/**
 *
 * @author kayum
 */
public class frmRegions extends javax.swing.JFrame {

    FonctionsMetier fm;
    ModelRegion mdlRegion;
    /**
     * Creates new form frmRegions
     */
    public frmRegions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegions = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnInserer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        cboSecteurs = new javax.swing.JComboBox<>();
        txtRegionNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblSecteur = new javax.swing.JLabel();
        lblGsb = new javax.swing.JLabel();
        lblFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tblRegions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblRegions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegions);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 102, 735, 146);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Les Regions");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(308, 27, 121, 29);

        btnInserer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn Insérer 2.png"))); // NOI18N
        btnInserer.setText("INSERER");
        btnInserer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsererMouseClicked(evt);
            }
        });
        getContentPane().add(btnInserer);
        btnInserer.setBounds(200, 330, 111, 23);

        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modifier2.png"))); // NOI18N
        btnModifier.setText("MODIFIER");
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });
        getContentPane().add(btnModifier);
        btnModifier.setBounds(390, 330, 110, 23);
        getContentPane().add(cboSecteurs);
        cboSecteurs.setBounds(466, 271, 147, 22);
        getContentPane().add(txtRegionNom);
        txtRegionNom.setBounds(150, 272, 170, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom de la Region:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(45, 276, 87, 13);

        lblSecteur.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        lblSecteur.setForeground(new java.awt.Color(255, 255, 255));
        lblSecteur.setText("Secteur");
        getContentPane().add(lblSecteur);
        lblSecteur.setBounds(388, 276, 60, 13);

        lblGsb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gsb.png"))); // NOI18N
        getContentPane().add(lblGsb);
        lblGsb.setBounds(20, 10, 115, 80);

        lblFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pour visiteur.jpg"))); // NOI18N
        getContentPane().add(lblFond);
        lblFond.setBounds(-7, -1, 760, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fm = new FonctionsMetier();
        // On crée notre modelJeux
        mdlRegion = new ModelRegion();
        // On charge les données dans le modèle
        mdlRegion.loadDatasRegion(fm.getAllRegions());
        // On met à jour le modèle du JTable
        tblRegions.setModel(mdlRegion);
        
        for (Secteur secteur : fm.getAllSecteurs())
        {
            cboSecteurs.addItem(secteur.getNomSecteur());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnInsererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsererMouseClicked
        // TODO add your handling code here:
        if(txtRegionNom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un nom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
            String nom = txtRegionNom.getText();
            int id = fm.getLastIdRegion();
            int secteur = fm.getIdSecteurByName(cboSecteurs.getSelectedItem().toString());

            Region region = new Region(id,nom);
            fm.insertRegion(region, secteur);

            mdlRegion.loadDatasRegion(fm.getAllRegions());
            // On met à jour le modèle du JTable
            tblRegions.setModel(mdlRegion);
        }
    }//GEN-LAST:event_btnInsererMouseClicked

    private void tblRegionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegionsMouseClicked
        // TODO add your handling code here:
        String nom = tblRegions.getValueAt(tblRegions.getSelectedRow(), 1).toString();
        String secteur = tblRegions.getValueAt(tblRegions.getSelectedRow(), 2).toString();
        
        txtRegionNom.setText(nom);
        cboSecteurs.setSelectedItem(secteur);
        
    }//GEN-LAST:event_tblRegionsMouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
        // TODO add your handling code here:
        if(txtRegionNom.getText().compareTo("") == 0)
        {
            // On affiche un message
            JOptionPane.showMessageDialog(null,
                    "Veuillez saisir un nom", "Erreur de saisie",
                    JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
        String nom = txtRegionNom.getText();
        int id = Integer.parseInt(tblRegions.getValueAt(tblRegions.getSelectedRow(), 0).toString());
        int secteur = fm.getIdSecteurByName(cboSecteurs.getSelectedItem().toString());
        
        Region region = new Region(id,nom);
        fm.modifierRegion(region.getNomRegion(), secteur, region.getCodeRegion());
        
        mdlRegion.loadDatasRegion(fm.getAllRegions());
        // On met à jour le modèle du JTable
        tblRegions.setModel(mdlRegion);
        }
    }//GEN-LAST:event_btnModifierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JComboBox<String> cboSecteurs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFond;
    private javax.swing.JLabel lblGsb;
    private javax.swing.JLabel lblSecteur;
    private javax.swing.JTable tblRegions;
    private javax.swing.JTextField txtRegionNom;
    // End of variables declaration//GEN-END:variables
}
