/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.Region;
import Tools.FonctionsMetier;
import Model.ModelRegion;
import Model.ModelVisiteur;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;

import javax.swing.UIManager;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;

import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author kayum
 */
public class frmStatistiques extends javax.swing.JFrame {

    FonctionsMetier fm;
    ModelRegion mdlRegion;
    ModelVisiteur mdlVisiteur;
    /**
     * Creates new form frmStatistiques
     */
    public frmStatistiques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSecteurParRegion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRegionPlus = new javax.swing.JLabel();
        lblRegionMoins = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPourcentageVisiteurs = new javax.swing.JTable();
        btnStatVisiteur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblSecteurParRegion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSecteurParRegion);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Nombres de secteurs par region");

        jLabel2.setText("La region ou travaille le plus de visiteurs:");

        jLabel3.setText("La region ou travaille le moins de visiteurs:");

        jLabel4.setText("Le pourcentage de visiteurs non responsable d'un secteur");

        lblRegionPlus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRegionPlus.setText("jLabel5");

        lblRegionMoins.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRegionMoins.setText("jLabel5");

        tblPourcentageVisiteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblPourcentageVisiteurs);

        btnStatVisiteur.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnStatVisiteur.setText(">> Sous forme graphique");
        btnStatVisiteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatVisiteurMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegionPlus)
                            .addComponent(lblRegionMoins))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnStatVisiteur))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRegionPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRegionMoins)
                        .addGap(40, 40, 40)
                        .addComponent(btnStatVisiteur)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        FonctionsMetier fm = new FonctionsMetier();
        // On crée notre modelJeux
        mdlRegion = new ModelRegion();
        // On charge les données dans le modèle
        mdlRegion.loadDatasStatistiques(fm.getAllRegionsParNbSecteur());
        // On met à jour le modèle du JTable
        tblSecteurParRegion.setModel(mdlRegion);
        // On crée notre modelJeux
        mdlVisiteur = new ModelVisiteur();
        // On charge les données dans le modèle
        mdlVisiteur.loadDatasStatistiques(fm.getPourcentageVisiteurs());
        // On met à jour le modèle du JTable
        tblPourcentageVisiteurs.setModel(mdlVisiteur);
       
        
        lblRegionPlus.setText(fm.getRegionAvecLePlusDeV());
        lblRegionMoins.setText(fm.getRegionAvecLeMoinsDeV());
        
    }//GEN-LAST:event_formWindowOpened

    private void btnStatVisiteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatVisiteurMouseClicked
        // TODO add your handling code here:
        // Camembert
        fm = new FonctionsMetier();
        ArrayList <Region> lesRegionsStats = new ArrayList<>();
        lesRegionsStats = fm.getAllRegionsParNbSecteur();
        
        DefaultPieDataset StatVisiteur = new DefaultPieDataset();
        for(Region statReg : lesRegionsStats)
        {
        StatVisiteur.setValue(statReg.getNomRegion(),statReg.getNbSecteurParRegion());
            //System.out.println(StatVisiteur);
        }
        JFreeChart chart1 = ChartFactory.createPieChart(
        "Nombre de régions par secteur ",
        StatVisiteur,
        true, // légende
        true, // info bulle
        false // url
        );
        ChartFrame Cardinaliteframe = new ChartFrame("Statistiques", chart1);
        Cardinaliteframe.setSize(350, 350);
        Cardinaliteframe.setVisible(true);
        //Cardinaliteframe.pack();
        Cardinaliteframe.setVisible(true);
    }//GEN-LAST:event_btnStatVisiteurMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStatistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStatistiques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStatVisiteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRegionMoins;
    private javax.swing.JLabel lblRegionPlus;
    private javax.swing.JTable tblPourcentageVisiteurs;
    private javax.swing.JTable tblSecteurParRegion;
    // End of variables declaration//GEN-END:variables
}
